# Generated by Django 4.1.4 on 2022-12-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_hitmen_assigned_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitmen',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, help_text='Manager assigned for this hitmen', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.manager'),
        ),
    ]
