# Generated by Django 4.1.4 on 2022-12-16 18:39

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='boss',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hitmen',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='manager',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='hitmen',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, help_text='Manager assigned for this hitmen', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.manager'),
        ),
    ]
