# Generated by Django 4.1.4 on 2022-12-17 02:24

import apps.users.managers.user_manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_boss_managers_alter_hitmen_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='boss',
            managers=[
                ('objects', apps.users.managers.user_manager.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='hitmen',
            managers=[
                ('objects', apps.users.managers.user_manager.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='manager',
            managers=[
                ('objects', apps.users.managers.user_manager.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.users.managers.user_manager.UserManager()),
            ],
        ),
    ]
