# Generated by Django 4.1.4 on 2022-12-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_remove_hitmen_status_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Brief description for the hit', max_length=50)),
                ('target_name', models.CharField(help_text='Name of the target to be terminated', max_length=30)),
                ('status_mission', models.CharField(choices=[('A', 'Assigned'), ('FA', 'Failed Assigned'), ('C', 'Completed')], help_text='Status of missson', max_length=2)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.hitmen')),
            ],
        ),
    ]
