# Generated by Django 4.1.4 on 2022-12-17 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_boss_managers_alter_hitmen_managers_and_more'),
        ('hits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.hitmen'),
        ),
    ]
