# Generated by Django 4.1.4 on 2022-12-18 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hits', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='hit',
            name='object_id',
        ),
        migrations.AddField(
            model_name='hit',
            name='assignment_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hitcreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
