# Generated by Django 4.1.4 on 2022-12-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hits', '0003_remove_hit_content_type_remove_hit_object_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='assignee',
        ),
        migrations.AddField(
            model_name='hit',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='hit',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
