# Generated by Django 4.1.4 on 2022-12-18 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hits', '0004_remove_hit_assignee_hit_content_type_hit_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='hit',
            name='object_id',
        ),
        migrations.AddField(
            model_name='hit',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Manager assigned for this hitmen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigee', to=settings.AUTH_USER_MODEL),
        ),
    ]
